services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    container_name: oki_technologies_app
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    depends_on:
      - mysql
      - redis
    restart: always

  mysql:
    image: mysql
    container_name: oki_technologies_mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      # MYSQL_USER: '${DB_USERNAME}'
      # MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql:/var/lib/mysql'
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: oki_technologies_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 256M
    ports:
      - '${PHPMYADMIN_PORT:-8080}:80'
    restart: always

  redis:
    image: 'redis:alpine'
    container_name: oki_technologies_redis
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    restart: always

volumes:
  mysql:
  redis:
